### ISSUE TITLE
it seems that index.html has only been partly refreshed in 0b195a6d8af8329d5c7d5defdfe87e45f4d481fc

### ISSUE THREAD

**Issue by xilun** [SimonSapin/wtf-8#11]
It seems that index.html has only been partly refreshed in 0b195a6d8af8329d5c7d5defdfe87e45f4d481fc

The change in index.src.html U+FFFF -> U+10000 is not reflected in index.html.

**Comment by SimonSapin** [comment]
Fixed, thanks! (I just forgot to run the generator again…)
