### ISSUE TITLE
Improper Decoding Algorithm

### ISSUE THREAD

**Issue by Dylan16807** [SimonSapin/wtf-8#5]
In section 4.2 the decoding algorithm says to unconditionally consume the character after a lead surrogate unit.  This results in improper decoding when there is a sequence of two lead surrogate units followed by a trail surrogate unit.  Three code points will be emitted instead of two.  The note at the end of the section suggests that only two code points should be emitted, and in fact the two implementations I checked (wtf-8.js and rust-wtf8) will emit two code points in this situation.

The algorithm should consume the next code unit if and only if it is a trail surrogate unit.

**Comment by SimonSapin** [comment]
Good catch, thanks!

**Comment by SimonSapin** [comment]
I pushed a fix in https://github.com/SimonSapin/wtf-8/commit/7cf8092a247365fe0d4621a589473d5792f47739#diff-1. How does it look?

**Comment by SimonSapin** [comment]
Closing as fixed. Please comment here in it still looks wrong.
