### ISSUE TITLE
encoding problem

### ISSUE THREAD

**Issue by programmerjake** [SimonSapin/wtf-8#8]
There's a bug in section 6.1:

If you try to encode a code point 0x800 you get 0xC0 0xA0 0x80, it should produce 0xE0 0xA0 0x80.

Similarly for 0x10000, you get 0xC0 0x90 0x80 0x80, it should produce 0xF0 0x90 0x80 0x80

**Comment by programmerjake** [comment]
Friendly ping since this hasn't seen any activity in a year.

**Comment by SimonSapin** [comment]
Uh, sorry I missed this the first time. Thanks!
